FROM php:8.4-cli

WORKDIR /var/www/html

RUN apt-get update && apt-get install -y \
    git \
    unzip \
    libpq-dev

RUN docker-php-ext-install pdo pdo_pgsql pgsql

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

COPY . .

RUN composer install --no-dev --optimize-autoloader

CMD if [ "$RUN_ROLE" = "websocket" ]; then \
        php artisan reverb:start --host=0.0.0.0 --port=$PORT; \
    else \
        php artisan serve --host=0.0.0.0 --port=$PORT; \
    fi

